# Default values for territory-service
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullnameOverride: "loventure-prod-territory-service"

service:
  name: territory-service
  type: ClusterIP
  port: 8084
  targetPort: 8084

deployment:
  replicaCount: 1
  image:
    repository: territory-service
    tag: "8615390"
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  env:
    - name: SERVER_PORT
      value: "8084"
    - name: SPRING_DATASOURCE_URL
      value: "jdbc:postgresql://10.164.96.2:5432/territory_db"
    - name: SPRING_DATASOURCE_USERNAME
      value: "postgres"
    - name: SPRING_DATASOURCE_PASSWORD
      value: "Enqjrdlemf1!"

postgres:
  enabled: false  # Using external Managed PostgreSQL with PostGIS

global:
  imageRegistry: docker.io/pitterpetter
  imagePullPolicy: IfNotPresent
  namespace: loventure-app
  environment: prod

