global:
  imageRegistry: docker.io/pitterpetter
  imagePullPolicy: IfNotPresent
  namespace: loventure-app
  environment: production
# Gateway Service Configuration
gateway:
  replicaCount: 2
  image:
    repository: gateway-service
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
  # loadBalancer:
  #   enabled: true
  #   ip: "34.22.65.113"  # GCP에서 할당된 정적 IP 주소를 여기에 입력
  #   ports:
  #     http: 80
  #     https: 443
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  spring:
    profile: production
  # Additional required settings for gateway subchart
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  serviceAccount:
    create: true
    annotations: {}
    name: ""
    automountServiceAccountToken: true
  podAnnotations: {}
  podSecurityContext:
    fsGroup: 2000
  securityContext:
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    runAsUser: 1000
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
  nodeSelector: {}
  tolerations: []
  affinity: {}
# Auth Service Configuration
auth-service:
  service:
    name: auth-service
    type: ClusterIP
    port: 8081
    targetPort: 8081
  deployment:
    replicaCount: 2
    image:
      repository: auth-service
      tag: "f3df464"
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
    env:
      - name: SPRING_PROFILES_ACTIVE
        value: "production"
      - name: SERVER_PORT
        value: "8081"
      - name: JWT_SECRET
        value: "yoursupersecurejwtsecretkeythatisatleast32characterslongforproductionusechangethis"
      - name: GOOGLE_CLIENT_ID
        value: "your-google-client-id"
      - name: GOOGLE_CLIENT_SECRET
        value: "your-google-client-secret"
      - name: KAKAO_CLIENT_ID
        value: "your-kakao-client-id"
      - name: KAKAO_CLIENT_SECRET
        value: "your-kakao-client-secret"
  postgres:
    enabled: true
    image:
      registry: docker.io
      repository: postgres
      tag: "14"
    service:
      port: 5432
    persistence:
      enabled: true
      size: 10Gi
      storageClass: ""
      accessMode: ReadWriteOnce
    auth:
      postgresPassword: "1234"
      database: "auth"
      username: "root"
# Content Service Configuration
content-service:
  service:
    name: content-service
    type: ClusterIP
    port: 8082
    targetPort: 8082
  deployment:
    replicaCount: 2
    image:
      repository: content-service
      tag: latest
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
    env:
      - name: SPRING_PROFILES_ACTIVE
        value: "production"
      - name: SERVER_PORT
        value: "8082"
  postgres:
    enabled: true
    image:
      registry: docker.io
      repository: postgres
      tag: "14"
    service:
      port: 5432
    persistence:
      enabled: true
      size: 10Gi
      storageClass: ""
      accessMode: ReadWriteOnce
    auth:
      postgresPassword: "1234"
      database: "content"
      username: "root"
# Course Service Configuration
course-service:
  service:
    name: course-service
    type: ClusterIP
    port: 8083
    targetPort: 8083
  deployment:
    replicaCount: 2
    image:
      repository: course-service
      tag: latest
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
    env:
      - name: SPRING_PROFILES_ACTIVE
        value: "production"
      - name: SERVER_PORT
        value: "8083"
  postgres:
    enabled: true
    image:
      registry: docker.io
      repository: postgres
      tag: "14"
    service:
      port: 5432
    persistence:
      enabled: true
      size: 10Gi
      storageClass: ""
      accessMode: ReadWriteOnce
    auth:
      postgresPassword: "1234"
      database: "course"
      username: "root"
# AI Service Configuration
ai-service:
  service:
    name: ai-service
    type: ClusterIP
    port: 8000
    targetPort: 8000
  deployment:
    replicaCount: 2
    image:
      repository: ai-service
      tag: latest
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512Mi
    env:
      - name: ENVIRONMENT
        value: "production"
      - name: PORT
        value: "8000"
# gateway-service:
#   deployment:
#     image:
#       tag: cb446c3
