{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis.fullname" . }}-config
  labels:
    {{- include "redis.labels" . | nindent 4 }}
data:
  redis.conf: |
    # Redis configuration for caching
    maxmemory 128mb
    maxmemory-policy allkeys-lru
    save ""
    appendonly no
    tcp-keepalive 300
    timeout 0
{{- end }}
