apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.loadBalancer.enabled }}
  annotations:
    cloud.google.com/load-balancer-type: "External"
    {{- if .Values.loadBalancer.sslCertificates }}
    cloud.google.com/load-balancer-ssl-certificates: {{ .Values.loadBalancer.sslCertificates }}
    cloud.google.com/load-balancer-backend-protocol: "HTTP"
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.loadBalancer.ip }}
  loadBalancerIP: {{ .Values.loadBalancer.ip }}
  {{- end }}
  ports:
    {{- if eq .Values.service.type "LoadBalancer" }}
    - name: http
      port: {{ .Values.loadBalancer.ports.http | default 80 }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
    - name: https
      port: {{ .Values.loadBalancer.ports.https | default 443 }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
    {{- else }}
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
    {{- end }}
  selector:
    {{- include "gateway.selectorLabels" . | nindent 4 }}
