apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "auth-service.fullname" . }}
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "auth-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "auth-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            {{- range .Values.deployment.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            - name: DB_HOST
              value: {{ include "auth-service.fullname" . }}-postgres.{{ .Values.global.namespace }}.svc.cluster.local
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: {{ .Values.postgres.auth.database }}
            - name: DB_USERNAME
              value: {{ .Values.postgres.auth.username }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "auth-service.fullname" . }}-postgres-secret
                  key: postgres-password
            - name: JWT_SECRET
              value: {{ .Values.global.jwtSecret | quote }}
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10      # 타임아웃을 10초로 증가
            failureThreshold: 3     # 3회 실패 시 재시작
            successThreshold: 1     # 1회 성공 시 Ready
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5       # 타임아웃을 5초로 증가
            failureThreshold: 3     # 3회 실패 시 제외
            successThreshold: 1     # 1회 성공 시 Ready
