# Default values for course-service
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullnameOverride: "loventure-prod-course-service"

service:
  name: course-service
  type: ClusterIP
  port: 8083
  targetPort: 8083

deployment:
  replicaCount: 1
  image:
    repository: course-service
    tag: "bfc68e6"
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  env:
    - name: SERVER_PORT
      value: "8083"
    - name: SPRING_DATASOURCE_URL
      value: "" # Set via ArgoCD UI
    - name: SPRING_DATASOURCE_USERNAME
      value: "" # Set via ArgoCD UI
    - name: SPRING_DATASOURCE_PASSWORD
      value: "" # Set via ArgoCD UI

postgres:
  enabled: false  # Using external Managed PostgreSQL

global:
  imageRegistry: docker.io/pitterpetter
  imagePullPolicy: IfNotPresent
  namespace: loventure-app
  environment: prod
