# Default values for content-service
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullnameOverride: "loventure-prod-content-service"

service:
  name: content-service
  type: ClusterIP
  port: 8082
  targetPort: 8082

deployment:
  replicaCount: 1
  image:
    repository: content-service
    tag: "5bc47a1"
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  env:
    - name: SERVER_PORT
      value: "8082"
    - name: SPRING_DATASOURCE_URL
      value: "" # Set via ArgoCD UI
    - name: SPRING_DATASOURCE_USERNAME
      value: "" # Set via ArgoCD UI
    - name: SPRING_DATASOURCE_PASSWORD
      value: "" # Set via ArgoCD UI
  volumeMounts:
    - name: gcs-credentials
      mountPath: /etc/gcp
      readOnly: true
  volumes:
    - name: gcs-credentials
      secret:
        secretName: gcs-service-account

gcs:
  bucketName: "" # Set via ArgoCD Parameters
  credentialsPath: "/etc/gcp/key.json"
  projectId: "" # Set via ArgoCD Parameters

postgres:
  enabled: false  # Using external Managed PostgreSQL

global:
  imageRegistry: docker.io/pitterpetter
  imagePullPolicy: IfNotPresent
  namespace: loventure-app
  environment: prod
