apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: argocd
spec:
  description: Default project for ArgoCD applications
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: 'apps'
    kind: Deployment
  - group: 'apps'
    kind: Service
  - group: 'apps'
    kind: StatefulSet
  - group: ''
    kind: Secret
  - group: ''
    kind: ConfigMap
  - group: ''
    kind: PersistentVolumeClaim
  - group: 'networking.k8s.io'
    kind: Ingress
  - group: 'extensions'
    kind: Ingress
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRole
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRoleBinding
  - group: 'apiextensions.k8s.io'
    kind: CustomResourceDefinition
  - group: 'argoproj.io'
    kind: Application
  - group: 'argoproj.io'
    kind: AppProject
  - group: 'argoproj.io'
    kind: ApplicationSet
