apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loventure-ai-service
  namespace: argocd
  labels:
    environment: production
    project: loventure
    service: ai
    priority: "2"  # Redis 이후 배포
spec:
  project: default
  source:
    repoURL: https://github.com/PitterPetter/PitterPatter-Manifest
    targetRevision: main
    path: charts/loventure/charts/ai-service
    helm:
      releaseName: loventure
      valueFiles:
        - values.yaml
      # AI Service 환경변수 (ArgoCD UI Parameters 탭에서 직접 수정 가능)
      # 실제 값은 ArgoCD UI에서 Parameters 탭에서 설정하세요
      parameters:
        - name: deployment.env[2].value
          value: ""  # SECRET_KEY: AI Service용 시크릿 키
  destination:
    server: https://kubernetes.default.svc
    namespace: loventure-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  revisionHistoryLimit: 10
