apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loventure-prod
  namespace: argocd
  labels:
    environment: production
    project: loventure
spec:
  project: default
  source:
    repoURL: https://github.com/PitterPetter/PitterPatter-Manifest
    targetRevision: main
    path: charts/loventure
    helm:
      valueFiles:
        - values.yaml
      # Production 환경 DB 접속 정보 및 AI Service SECRET_KEY 설정
      parameters:
        # Gateway JWT Secret
        - name: gateway.jwtSecret
          value: "" # ArgoCD UI에서 실제 값 설정
        # Auth Service DB 접속 정보
        - name: auth-service.deployment.env[1].value
          value: "" # SPRING_DATASOURCE_URL
        - name: auth-service.deployment.env[2].value
          value: "" # SPRING_DATASOURCE_USERNAME
        - name: auth-service.deployment.env[3].value
          value: "" # SPRING_DATASOURCE_PASSWORD
        # Content Service DB 접속 정보
        - name: content-service.deployment.env[1].value
          value: "" # SPRING_DATASOURCE_URL
        - name: content-service.deployment.env[2].value
          value: "" # SPRING_DATASOURCE_USERNAME
        - name: content-service.deployment.env[3].value
          value: "" # SPRING_DATASOURCE_PASSWORD
        # Course Service DB 접속 정보
        - name: course-service.deployment.env[1].value
          value: "" # SPRING_DATASOURCE_URL
        - name: course-service.deployment.env[2].value
          value: "" # SPRING_DATASOURCE_USERNAME
        - name: course-service.deployment.env[3].value
          value: "" # SPRING_DATASOURCE_PASSWORD
        # Territory Service DB 접속 정보
        - name: territory-service.deployment.env[1].value
          value: "" # SPRING_DATASOURCE_URL
        - name: territory-service.deployment.env[2].value
          value: "" # SPRING_DATASOURCE_USERNAME
        - name: territory-service.deployment.env[3].value
          value: "" # SPRING_DATASOURCE_PASSWORD
        # AI Service SECRET_KEY
        - name: ai-service.deployment.env[2].value
          value: "" # SECRET_KEY
  destination:
    server: https://kubernetes.default.svc
    namespace: loventure-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  revisionHistoryLimit: 10
