# Default values for auth-service
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullnameOverride: "loventure-prod-auth-service"

service:
  name: auth-service
  type: ClusterIP
  port: 8081
  targetPort: 8081

deployment:
  replicaCount: 1
  image:
    repository: auth-service
    tag: "31b5ea9"
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  env:
    - name: SERVER_PORT
      value: "8081"
    - name: SPRING_DATASOURCE_URL
      value: "jdbc:postgresql://10.164.96.2:5432/auth_db"
    - name: SPRING_DATASOURCE_USERNAME
      value: "postgres"
    - name: SPRING_DATASOURCE_PASSWORD
      value: "Enqjrdlemf1!"

postgres:
  enabled: false  # Using external PostgreSQL
  image:
    registry: docker.io
    repository: postgres
    tag: "14"
  service:
    port: 5432
  persistence:
    enabled: true
    size: 10Gi
    storageClass: ""
    accessMode: ReadWriteOnce
  auth:
    postgresPassword: "" # Set via ArgoCD UI
    database: "auth"
    username: "root"

global:
  imageRegistry: docker.io/pitterpetter
  imagePullPolicy: IfNotPresent
  namespace: loventure-app
  environment: prod