# Default values for auth-service
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullnameOverride: "loventure-prod-auth-service"

service:
  name: auth-service
  type: ClusterIP
  port: 8081
  targetPort: 8081

deployment:
  replicaCount: 1
  image:
    repository: auth-service
    tag: "7653931"
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  env:
    - name: SERVER_PORT
      value: "8081"
    - name: SPRING_DATASOURCE_URL
      value: "" # Set via ArgoCD UI
    - name: SPRING_DATASOURCE_USERNAME
      value: "" # Set via ArgoCD UI
    - name: SPRING_DATASOURCE_PASSWORD
      value: "" # Set via ArgoCD UI

postgres:
  enabled: false  # Using external Managed PostgreSQL

global:
  imageRegistry: docker.io/pitterpetter
  imagePullPolicy: IfNotPresent
  namespace: loventure-app
  environment: prod